default:
  tags:
    - kubernetes
  image:
    ubuntu:20.04

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -yqq g++ cmake libgtest-dev
    - apt-get install -yqq python3-dev 
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cd $CI_PROJECT_DIR
  script:
    - mkdir build && cd build
    - cmake ..
    - echo "compiling with $(nproc) cores"
    - make -j $(nproc)
    - ./barnes-hut
    - ./tests


test-job:
  stage: test
  script:
    - echo "I would like to run ./tests in here, but don't know how"

