default:
  tags:
    - kubernetes
  image:
    ubuntu:20.04

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  artifacts:
    untracked: true
  before_script:
    - apt-get update
    - apt-get install -yqq g++ cmake libgtest-dev
    - apt-get install -yqq python3-dev 
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cd $CI_PROJECT_DIR
  script:
    - mkdir build && cd build
    - cmake ..
    - echo "compiling with $(nproc) cores"
    - make barnes-hut -j $(nproc)
    - make tests -j $(nproc)


test-job:
  stage: test
  dependencies: 
    - build
  script:
    - cd $CI_PROJECT_DIR
    - cd build
    - ./tests


