default:
  tags:
    - kubernetes
  image:
    ubuntu:20.04

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  artifacts:
    untracked: true
  before_script:
    - apt-get update
    - apt-get install -yqq build-essential
    - apt-get install -yqq g++-11
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
    - update-alternatives --auto gcc
    - apt-get install -yqq cmake libgtest-dev libglm-dev
    - apt-get install -yqq python3-dev 
    - cd /usr/src/gtest
    - cmake CMakeLists.txt && make
    - cd $CI_PROJECT_DIR
  script:
    - mkdir build && cd build
    - cmake ..
    - echo "compiling with $(nproc) cores"
    - make -j $(nproc)


test-job:
  stage: test 
  script:
    - cd $CI_PROJECT_DIR
    - cd build
    - ./tests/tests  --gtest_output=xml:xunit.xml
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - build/tests/xunit.xml
    reports:
      junit: build/tests/xunit.xml


